#!/usr/bin/perl

#use Switch;
#use strict;
use warnings;
use feature qw(switch say);

require '/home/grb.exttrig/Online/O2/processor/exttrig_utils.pl';
require '/home/grb.exttrig/Online/O2/processor/exttrig_params.pl';

#=== Get user name ===#
$USERNAME = `whoami`;
chomp($USERNAME);

#=== Specify debug level ===#
$DEBUGLVL = 1;

#=== Specify local working directories ===#
$HOMEDIR    = sprintf "/home/%s", $USERNAME;
$GRBDIR     = sprintf "%s/Online/%s/grbs", $HOMEDIR, $LIGORUN;
$SCRIPTSDIR = sprintf "%s/Online/%s/processor", $HOMEDIR, $LIGORUN;
$WEBDIR     = sprintf "%s/Online/%s/processor/web", $HOMEDIR, $LIGORUN;
$JOBSDIR    = sprintf "%s/runs/CBC", $SCRIPTSDIR;
$PARAMSDIR  = sprintf "%s/params/CBC", $SCRIPTSDIR;
$PUBSERVER_SED = $PUBSERVER;
my $find = "//";
my $replace = "\\/\\/";
$PUBSERVER_SED =~s/$find/$replace/g;
$RESULTSURL = sprintf "%s\\/~%s\\/grb\\/online\\/%s", $PUBSERVER_SED, $USERNAME, $LIGORUN;
$MAINWEBDIR = sprintf "%s/~%s/grb/online/%s", $PUBSERVER, $USERNAME, $LIGORUN;
$MAINURL    = sprintf "%s/~%s/web/%s/OnlineGRB_page_%s.html", $PUBSERVER, $USERNAME, $LIGORUN, $LIGORUN;
$PUBLICDIR  = sprintf "%s/public_html/grb/online/%s", $HOMEDIR, $LIGORUN;

#=== Specify output html file ===#
$htmlFile = sprintf "%s/OnlineGRB_page_%s.html", $WEBDIR, $LIGORUN;

#=== Specify line offset for job status line in html file ===#
$lineOffset = 10;


#=== Set start time ===#
$currentDelay = $MONDELAY + 1;

    #=== Update time of scp ===#
    $previousTime = time;

    #=== Open input search status file ===#
    $processStatusFile = sprintf "%s/processedjobs_cohptf_%s.log", $SCRIPTSDIR, $LIGORUN;
    $tempFile          = sprintf "%s/processedjobs_cohptf_%s_temp.log", $SCRIPTSDIR, $LIGORUN;
    open PROCSTAT, "<$processStatusFile"
      or die "Error opening input search status file $processStatusFile: $!";
    chomp(@procStats = <PROCSTAT>);
    close PROCSTAT;

    #=== Open output open-box status file ===#
    $openboxFile = sprintf "%s/openboxjobs_cohptf_%s.log", $SCRIPTSDIR, $LIGORUN;
    open OPENBOX, ">>$openboxFile"
      or die "Error opening output open-box status file $openboxFile: $!";


    #=== Loop through GRBs ===#
    foreach $procStat (@procStats) {
      ($grbName,$grbGPS,$grbDate,$grbTime,$grbRA,$grbDec,$grbError,$ifoString,$grbSat,$grbTrigDur,
       $jobCluster,$latency,$jobRunTime,$jobStatus,$rescueCtr,$procjobCluster,$runTime,$procjobStatus,$procrescueCtr) = split(' ',$procStat);

      #=== Set default results link ===#
      $resultsLink = '';

      #=== Set default open box link ===#
      $openboxLink = '';

      $PPfile = '';

      #=== If condor job was submitted, check on jobs ===#
      if ($procjobStatus ne 'PROCESSED' && $jobStatus ne 'DATACUT' && $jobStatus ne 'RESCUE') {
        $condorCommand = sprintf "condor_q -nobatch %d", $procjobCluster;
        @condorResult  = ();
        @condorResult  = `$condorCommand`;
        chomp(@condorResult);

        #=== If job is not found ===#
        #if ($#condorResult < 4) {
        if ($#condorResult < 6) {
          printf "number of lines = $#condorResult\n";
          $failFetchFlag = 0;
          if ($#condorResult+1 == 0) {
            $failFetchFlag = 1;
          }

          if ($failFetchFlag == 0) {
            #=== Specify directory for post-processing jobs ===#
            $grblogdir = sprintf "/home/grb.exttrig/log/%s/GRB%s", $LIGORUN, $grbName;
            opendir $dh, $grblogdir or die "Could not open '$grblogdir' for reading '$!'\n";
            my @contents = grep {$_ ne '.' and $_ ne '..'} readdir $dh;
            foreach my $content (@contents) {
            $pygrbtmp = $content;
            print "$content\n";
            }
            closedir $dh;
            $Pegasusjobdir = sprintf "%s/%s/work", $grblogdir, $pygrbtmp;
            $jobGrbDir = sprintf "GRB%s", $grbName;
            $jobDir    = sprintf "%s/%s", $JOBSDIR, $jobGrbDir;
            $grbDir  = sprintf "%s/%s", $jobDir, $jobGrbDir;

            $xcheckCommand = sprintf "python CBCcheckgrboutput.py -t %s -g %s -j PP", $Pegasusjobdir, $grbDir;
            @xcheckResult  = ();
            @xcheckResult  = `$xcheckCommand`;
            chomp(@xcheckResult);
            foreach $xcheckLine (@xcheckResult) {
              if ($xcheckLine =~ /No output trigcluster file missing/i) {
               $PPfile = 'ALLPRESENT';
             }
            }
            #=== Check if a rescue file exists ===#
            if ($PPfile ne 'ALLPRESENT'){
            @jobdirFiles = ();
            $lsCommand   = sprintf "ls $Pegasusjobdir";
            @jobdirFiles = `$lsCommand`;
            chomp(@jobdirFiles);
            $rescueDag = '';
            foreach $jobdirLine (@jobdirFiles) {
              if ($jobdirLine =~ /(pygrb_offline-0\.dag)\.rescue(\d+)/) {
                $rescueDag = $1;
                  $rescueNum = $2;
                  if ($rescueNum > $procrescueCtr) {
                    $procjobStatus = 'RESCUE';            
                    $rescueCommand = sprintf "pegasus-run %s", $Pegasusjobdir;
                    $procjobCluster = 0;
                    $runTime = '0+00:00:00';
                    printf "$rescueCommand\n";
                    chdir "$grbDir";
                    @rescueResult = ();
                    @rescueResult = `$rescueCommand`;
                    $procrescueCtr++;
                    chomp(@rescueResult);
                    foreach $rescueLine (@rescueResult) {
                      if ($rescueLine =~ /cluster (\d+)/) {
                        $procjobCluster = $1;
                        last;
                      }
                    }
                    chdir "$SCRIPTSDIR";
                    last;
                  } else{
                  $procjobStatus = 'RUNNING';
                  }
              }
            }
           }

            if ($procjobStatus ne 'RESCUE' && $PPfile eq 'ALLPRESENT') {
              #=== Set status to processed ===#
              $procjobStatus = 'PROCESSED';
 
              #$Closedhtml = sprintf "%s/GRB%s/summary.html", $PUBLICDIR, $grbName;
              #$Closedhtmlto = sprintf "%s/GRB%s/CLOSED_summary.html", $PUBLICDIR, $grbName;
              #$cpCommandclosed = sprintf "cp %s %s", $Closedhtml, $Closedhtmlto;
              #system "$cpCommandclosed";
           
              $resultsLink = sprintf "%s\\/GRB%s\\/GRB%s_CLOSED\\/summary.html", $RESULTSURL, $grbName, $grbName;
              &sendResultsMessage;
 
              printf OPENBOX "%s %10.0f %s %s %s %10s %-9s\n", $grbName, $grbGPS, $grbDate, $ifoString, $grbSat, '0000000', 'RUNNING';
            }
          }
        } else {
          #=== Parse the condor_q output ===#
          #$condorLine = $condorResult[$#condorResult];
          $condorLine = $condorResult[$#condorResult-2];
          ($clusterID,$ownerName,$submitDate,$submitTime, 
             $runTime,$runStatus,$runPriority,$runSize,$runCommand) = 
               split(' ',$condorLine);
          printf "$clusterID $ownerName $submitDate $submitTime ";
          printf "$runTime $runStatus $runPriority $runSize $runCommand\n";

          #=== Specify job status explicitly ===#
          #switch ($runStatus) {
          #  case 'R' { $procjobStatus = 'RUNNING'; }
          #  case 'I' { $procjobStatus = 'IDLE';    }
          #  case 'H' { $procjobStatus = 'HELD';    }
          given ($runStatus) {
            when ('R') { $procjobStatus = 'RUNNING'; }
            when ('I') { $procjobStatus = 'IDLE';    }
            when ('H') { $procjobStatus = 'HELD';    }
          }
        }

        #=== Check if this GRB has an entry in the output monitor file ===#
        $sedCommand = sprintf "sed -n '/^%s /=' %s", $grbName, $processStatusFile;
        $lineNumber = -1;
        $lineNumber = `$sedCommand`;
        chomp($lineNumber);

        if ($lineNumber =~ /^[1-9]/) {
          $monitorString = sprintf "%s %10.0f %s %s %s %f %7.3f %-12s %s %7.3f %10s %s %12s %-9s %03d %10s %12s %-9s %03d", 
                           $grbName, $grbGPS, $grbDate, $grbTime, $grbRA, $grbDec, $grbError, $ifoString, $grbSat, $grbTrigDur,
                           $jobCluster, $latency, $jobRunTime, $jobStatus, $rescueCtr,
                           $procjobCluster, $runTime, $procjobStatus, $procrescueCtr;
          $sedCommand = sprintf "sed '%ds/.*/%s/' %s > %s", 
                        $lineNumber, $monitorString, $processStatusFile, $tempFile;
          system $sedCommand;

          $cpCommand = sprintf "cp %s %s", $tempFile, $processStatusFile;
          system $cpCommand;
        }
        #=== Endif GRB has an entry in the monitor file ===#

        #=== Update search status web page ===#
        $searchStatusTable = {};
        $searchStatusTable->{'GRB_NAME'}    = $grbName;
        $searchStatusTable->{'GRB_GPS'}     = $grbGPS;
        $searchStatusTable->{'GRB_DATE'}    = $grbDate;
        $searchStatusTable->{'GRB_TIME'}    = $grbTime;
        $searchStatusTable->{'GRB_RA'}      = $grbRA;
        $searchStatusTable->{'GRB_DEC'}     = $grbDec;
        $searchStatusTable->{'GRB_ERR'}     = $grbError;
        $searchStatusTable->{'IFO_STRING'}  = $ifoString;
        $searchStatusTable->{'GRB_SAT'}     = $grbSat;
        $searchStatusTable->{'TRIG_DUR'}    = $grbTrigDur;
        $searchStatusTable->{'JOB_CLUSTER'} = $procjobCluster;
        $searchStatusTable->{'LATENCY'}     = $latency;
        $searchStatusTable->{'RUN_TIME'}    = $runTime;
        $searchStatusTable->{'JOB_STATUS'}  = $procjobStatus;

        updateWebStatusPTF($searchStatusTable,$htmlFile,$lineOffset,$resultsLink,$openboxLink);
      }
      #= Endif condor job was submitted, check on jobs =#
    }
    #=== End loop through GRBs ===#

    close OPENBOX;

sub sendResultsMessage {

  $emailsFile   = sprintf "%s/eventadvocate/%s_grbemails.txt", $SCRIPTSDIR, $grbName;
  $messagesFile = sprintf "%s/grbmessages_%s.log", $SCRIPTSDIR, $LIGORUN;

  #=== Specify pages with results ===#
  $resultsPageClosed = sprintf "%s/GRB%s/GRB%s_CLOSED/summary.html", $MAINWEBDIR, $grbName, $grbName;
  $resultsPageOpen   = '';

  #=== Note finish time of analysis ===#
  $gpsTime    = `lalapps_tconvert now`;
  chomp($gpsTime);

  #=== Calculate processing time in hours ===#
  $processTime = 0;
  $processTime = ($gpsTime - $grbGPS)/3600.0;
  $processTime = sprintf "%5.3f", $processTime;
  if ($processTime < 0) {
    $processTime = 0;
  }

  $eheaderTable = {};
  $eheaderTable->{'SUBJECT'} = sprintf "[PyGRB] GRB %s processed", $grbName;

  #=== Construct the message ===#
  $noticeString = sprintf "GRB %s has been processed, %8.3f hours after the trigger.", 
                               $grbName, $processTime;
         if ($ANNOTATEFLAG eq 'YES') {
         $annotateFile = sprintf "%s/annotateGraceDB_CBC_offsource_template.py", $SCRIPTSDIR;
         $catCommand = sprintf "cat %s | sed -e 's/EVENT_ID/%s/g' -e 's/USERNAME/%s/g' -e 's/LIGORUN/%s/g' -e 's/PUBSERVER/%s/g'> annotateGraceDB.py", $annotateFile, $grbName, $USERNAME, $LIGORUN, $PUBSERVER_SED;
         system $catCommand;
         $annotateCommand = sprintf "python annotateGraceDB.py";
         system $annotateCommand;
         $rmCommand = sprintf "rm -f annotateGraceDB.py";
         system $rmCommand;

         $annotateFile = sprintf "%s/logGraceDB_CBC_end_template.py", $SCRIPTSDIR;
         $catCommand = sprintf "cat %s | sed -e 's/EVENT_ID/%s/g' -e 's/HOUR/%s/g'> logGraceDB.py", $annotateFile, $grbName, $processTime;
         system $catCommand;
         $logCommand = sprintf "python logGraceDB.py";
         system $logCommand;
         $rmCommand = sprintf "rm -f logGraceDB.py";
         system $rmCommand;
         }
  $noticeString = sprintf "%s\n\nClosed box results:", $noticeString;
  $noticeString = sprintf "%s\n<%s>", $noticeString, $resultsPageClosed;
  $noticeString = sprintf "%s\n\nOpen box results:", $noticeString;
  $noticeString = sprintf "%s\n<%s>", $noticeString, $resultsPageOpen;
  $noticeString = sprintf "%s\n\nMain results page:", $noticeString;
  $noticeString = sprintf "%s\n<%s>\n", $noticeString, $MAINURL;

  $eheaderTable->{'MESSAGE'} = $noticeString;

  printf "$noticeString\n";

  #=== Send the message ===#
  grbNotify($eheaderTable,$emailsFile,$messagesFile);
}

#=== End monitorPostproc ===#
