#!/usr/bin/perl -w

require '/home/grb.exttrig/Online/O2/processor/exttrig_params.pl';

#=== Get user name ===#
$USERNAME = `whoami`;
chomp($USERNAME);

#=== Specify local working directories ===#
$HOMEDIR    = sprintf "/home/%s", $USERNAME;
$SCRIPTSDIR = sprintf "%s/Online/%s/processor", $HOMEDIR, $LIGORUN;
$WEBDIR     = sprintf "%s/Online/%s/processor/web", $HOMEDIR, $LIGORUN;

#=== Specify output html file ===#
$copyfrom = sprintf "%s/OnlineGRB_page_%s.html", $WEBDIR, $LIGORUN;
$copyto = sprintf "%s/public_html/web/%s/OnlineGRB_page_%s.html", $HOMEDIR, $LIGORUN, $LIGORUN;

$Copywebfile = sprintf "python %s/copyWebtoPublichtml.py --copyfrom $copyfrom --copyto $copyto", $SCRIPTSDIR;
system $Copywebfile;
