#!/usr/bin/perl

use Switch;

require 'exttrig_utils.pl';
require 'exttrig_params.pl';

#=== Get user name ===#
$USERNAME = `whoami`;
chomp($USERNAME);

#=== Specify local working directories ===#
$HOMEDIR    = sprintf "/home/%s", $USERNAME;
$GRBDIR     = sprintf "%s/Online/%s/grbs", $HOMEDIR, $LIGORUN;
$SCRIPTSDIR = sprintf "%s/Online/%s/processor", $HOMEDIR, $LIGORUN;
$WEBDIR     = sprintf "%s/Online/%s/processor/web", $HOMEDIR, $LIGORUN;
$JOBSDIR    = sprintf "%s/runs/X", $SCRIPTSDIR;
$PROCWEBDIR = sprintf "%s/public_html/grb/online/%s/search/results", $HOMEDIR, $LIGORUN;
$LOGDIR     = sprintf "/usr1/%s/log", $USERNAME;

#=== Specify output html file ===#
$htmlFile = sprintf "%s/OnlineGRB_page_%s.html", $WEBDIR, $LIGORUN;

#=== Specify line offset for job status line in html file ===#
$lineOffset = 3;

#=== Set sleep time in seconds between monitoring periods ===#

#=== Set start time ===#
$currentDelay = $MONDELAY + 1;

#while (1) {

  #=== If MONDELAY seoconds has elapsed since last monitor ===#
#  if ($currentDelay >= $MONDELAY) {

    #=== Update time of scp ===#
    $previousTime = time;

    #=== Open input search status file ===#
    #$processStatusFile = sprintf "%s/xprocess_status_%s.txt", $SCRIPTSDIR, $LIGORUN;
    $processStatusFile = sprintf "%s/monitor_status_%s.log", $SCRIPTSDIR, $LIGORUN;
    open PROCSTAT, "<$processStatusFile"
      or die "Error opening input search status file $processStatusFile: $!";
    chomp(@procStats = <PROCSTAT>);
    close PROCSTAT;

    #=== Open output monitor status file ===#
    $monitorStatusFile = sprintf "%s/monitor_status_%s.log", $SCRIPTSDIR, $LIGORUN;
    $tempFile = sprintf "%s/monitor_status_%s_temp.log", $SCRIPTSDIR, $LIGORUN;
    #open MONSTAT, ">>$monitorStatusFile"
    #  or die "Error opening output monitor file $monitorStatusFile: $!";

    #=== Open output processed jobs file ===#
    $processedJobsFile = sprintf "%s/processedjobs_%s.log", $SCRIPTSDIR, $LIGORUN;
    open PROCJOB, ">>$processedJobsFile"
      or die "Error opening output processed jobs file $processedJobsFile: $!";


    #=== Possible status descriptions ===#
    # PROCESSED
    # SUBMITTED
    # DATACUT
    # RUNNING
    # IDLE
    # HELD

    #=== Loop through GRBs ===#
    foreach $procStat (@procStats) {
      ($grbName,$grbGPS,$grbDate,$grbTime,$grbRA,$grbDec,$grbError,$ifoString,$grbSat,$jobCluster,$latency,$jobRunTime,$jobStatus,$rescueCtr) = split(' ',$procStat);

      if ($grbName eq '') {
        next;
      }

      if ($jobStatus eq 'NOFRAMES') {
        if (length($ifoString) < 3) {
          $jobStatus = 'DATACUT';
        } else {
          #=== Update search status web page ===#
          $searchStatusTable = {};
          $searchStatusTable->{'GRB_NAME'}      = $grbName;
          $searchStatusTable->{'GRB_GPS'}       = $grbGPS;
          $searchStatusTable->{'GRB_DATE'}      = $grbDate;
          $searchStatusTable->{'GRB_TIME'}      = $grbTime;
          $searchStatusTable->{'GRB_RA'}        = $grbRA;
          $searchStatusTable->{'GRB_DEC'}       = $grbDec;
          $searchStatusTable->{'GRB_ERR'}       = $grbError;
          $searchStatusTable->{'IFO_STRING'}    = $ifoString;
          $searchStatusTable->{'GRB_SAT'}       = $grbSat;
          $searchStatusTable->{'JOB_CLUSTER'}   = $jobCluster;
          $searchStatusTable->{'LATENCY'}       = $latency;
          $searchStatusTable->{'RUN_TIME'}      = $jobRunTime;
          $searchStatusTable->{'JOB_STATUS'}    = $jobStatus;
          $searchStatusTable->{'RESCUE_CTR'}    = $rescueCtr;

          $resultsLink = '';
          updateWebStatus($searchStatusTable,$htmlFile,$lineOffset,$resultsLink);

          next;
        }
      } 


      #=== If condor job was submitted, check on jobs ===#
      if ($jobStatus ne 'PROCESSED' && ($jobStatus ne 'RESCUE' || $jobCluster != 0)) {
        $condorCommand = sprintf "condor_q %d", $jobCluster;
        @condorResult  = ();
        @condorResult  = `$condorCommand`;
        chomp(@condorResult);

        #=== If job is not found ===#
        if ($#condorResult < 4) {
          #=== Append GRB to output processed jobs file ===#
          if ($jobStatus ne 'DATACUT' && $#condorResult+1 != 0) {
            #=== Check if job outputs are complete ===#
            $jobDir = sprintf "%s/GRB%s", $JOBSDIR, $grbName;
            $xcheckCommand = sprintf "xcheckgrboutput.py -d %s", $jobDir;
            @xcheckResult  = ();
            @xcheckResult  = `$xcheckCommand`;
            chomp(@xcheckResult);
            $rescueFlag = 0;
            foreach $xcheckLine (@xcheckResult) {
              if ($xcheckLine =~ /No output files missing/i) {
                $jobStatus = 'PROCESSED';
                last;
              }
            }

            if ($jobStatus ne 'PROCESSED') {
              $jobStatus  = 'RESCUE';
              $rescueFlag = 1;
              #=== Run rescue dag ===#
              @jobdirFiles = ();
              $lsCommand   = sprintf "ls $jobDir";
              @jobdirFiles = `$lsCommand`;
              chomp(@jobdirFiles);
              $rescueDag = '';
              foreach $jobdirLine (@jobdirFiles) {
                if ($jobdirLine =~ /(grb_alljobs\.dag)\.rescue(\d+)/) {
                  $rescueDag = $1;
                  #if ($rescueDag =~ /(\d+)/) {
                    $rescueNum = $2;
                    if ($rescueNum > $rescueCtr) {
                      #$rescueCommand = sprintf "condor_submit_dag %s", $rescueDag;
                      $rescueCommand = sprintf "condor_submit_dag grb_alljobs.dag";
                      $jobCluster = 0;
                      $jobRunTime = '0+00:00:00';
                      printf "$rescueCommand\n";
                      chdir "$jobDir";
                      @rescueResult = ();
                      @rescueResult = `$rescueCommand`;
                      $rescueCtr++;
                      chomp(@rescueResult);
                      foreach $rescueLine (@rescueResult) {
                        if ($rescueLine =~ /cluster (\d+)/) {
                          $jobCluster = $1;
                          last;
                        }
                      }   
                      chdir "$SCRIPTSDIR";
                      last;
                    }
                  #}
                }
              }
            }
          }
        } else {
          #=== Parse the condor_q output ===#
          $condorLine = $condorResult[$#condorResult];
          ($clusterID,$ownerName,$submitDate,$submitTime, 
             $jobRunTime,$runStatus,$runPriority,$runSize,$runCommand) = 
               split(' ',$condorLine);
          printf "$clusterID $ownerName $submitDate $submitTime ";
          printf "$jobRunTime $runStatus $runPriority $runSize $runCommand\n";

          #=== Specify job status explicitly ===#
          switch ($runStatus) {
            case 'R' { $jobStatus = 'RUNNING'; }
            case 'I' { $jobStatus = 'IDLE';    }
            case 'H' { $jobStatus = 'HELD';    }
          }
        }

        #=== Check if this GRB has an entry in the output monitor file ===#
        $sedCommand = sprintf "sed -n '/^%s /=' %s", $grbName, $monitorStatusFile;
        $lineNumber = -1;
        $lineNumber = `$sedCommand`;
        chomp($lineNumber);

        if ($lineNumber =~ /^[1-9]/) {
          #=== If the GRB already has an entry,  ===#
          #=== replace the entry with new status ===#
          if ($jobStatus eq 'PROCESSED' || $jobStatus eq 'DATACUT') {
            #=== Delete entry from monitor file ===#
            $sedCommand = sprintf "sed '%dd' %s > %s", 
                     $lineNumber, $monitorStatusFile, $tempFile;

            $procjobCluster = 0;
            $procjobRunTime = '--';
            $procjobStatus  = '--';
            $procrescueCtr  = 0;

            if ($jobStatus eq 'PROCESSED') {
              #==== Launch post-processing job ===#
              $jobDir = sprintf "%s/GRB%s", $JOBSDIR, $grbName;
              chdir "$jobDir";

              $prepPageCommand = sprintf "xgrbwebpage.py  \\
                --grb-name %s \\
                --user-tag online \\
                --veto-method medianAlphaCutCirc \\
                --percentile 99-99 \\
                --add-stat powerlaw \\
                --grb-dir %s \\
                --auto-dir %s \\
                --web-dir %s \\
                --log-dir %s --priority 20", $grbName, $jobDir, $jobDir, $PROCWEBDIR, $LOGDIR;
                # --log-dir %s --priority 20", $grbName, $jobDir, $jobDir, $PROCWEBDIR, $LOGDIR;

              $prepPageResult = 1;
              $prepPageResult = system $prepPageCommand;

              # === Put (ER6) resource allocation to sub files #
              $AUTO_WEB = sprintf "%s/auto_web", $jobDir; 
              chdir "$AUTO_WEB";
              $XTUNE_SUB = sprintf "xtunegrbwebpage.sub";
              $XMAKEVETO_SUB = sprintf "xmakegrbwebpage_vetoTest.sub";
              $XMAKEUL_SUB = sprintf "xmakegrbwebpage_ul.sub";
              $XMAKETUNE_SUB = sprintf "xmakegrbwebpage_tunedUL.sub";
              $XMAKEOPEN_SUB = sprintf "xmakegrbwebpage_open.sub";
              $sedCommand_xtune = sprintf "sed -i 's/notification = never/notification = never\\nRequirements = (TARGET.Online_Burst_GRB =?= True)\\n+Online_Burst_GRB = True/g' %s", $XTUNE_SUB;
              system $sedCommand_xtune;
              $sedCommand_xmakeveto = sprintf "sed -i 's/notification = never/notification = never\\nRequirements = (TARGET.Online_Burst_GRB =?= True)\\n+Online_Burst_GRB = True/g' %s", $XMAKEVETO_SUB;
              system $sedCommand_xmakeveto;
              $sedCommand_xmakeul = sprintf "sed -i 's/notification = never/notification = never\\nRequirements = (TARGET.Online_Burst_GRB =?= True)\\n+Online_Burst_GRB = True/g' %s", $XMAKEUL_SUB;
              system $sedCommand_xmakeul;
              $sedCommand_xmaketune = sprintf "sed -i 's/notification = never/notification = never\\nRequirements = (TARGET.Online_Burst_GRB =?= True)\\n+Online_Burst_GRB = True/g' %s", $XMAKETUNE_SUB;
              system $sedCommand_xmaketune;
              $sedCommand_xmakeopen = sprintf "sed -i 's/notification = never/notification = never\\nRequirements = (TARGET.Online_Burst_GRB =?= True)\\n+Online_Burst_GRB = True/g' %s", $XMAKEOPEN_SUB;
              system $sedCommand_xmakeopen;

              chdir "$jobDir"; 
              #######################################################
 

              $makePageCommand = sprintf "run_xmakegrbwebpageDAGJob_online_%s.sh", $grbName;
              @makePageResult = ();
              @makePageResult = `sh $makePageCommand`;
              chomp(@makePageResult);

              $procjobCluster = 0;
              foreach $resultLine (@makePageResult) {
                printf "$resultLine\n";
                if ($resultLine =~ /cluster (\d+)/) {
                  $procjobCluster = $1;
                  last;
                }
              }
              if ($procjobCluster != 0) {
                $procjobStatus = 'SUBMITTED';
              }
              chdir "$SCRIPTSDIR";
            }

            printf PROCJOB "%s %10.0f %s %s %7.3f %7.3f %7.3f %s %s %s %s %s %s %03d %s %s %s %03d\n", 
                            $grbName, $grbGPS, $grbDate, $grbTime, $grbRA, $grbDec, $grbError, $ifoString, $grbSat,
                            $jobCluster, $latency, $jobRunTime, $jobStatus, $rescueCtr,
                            $procjobCluster, $procjobRunTime, $procjobStatus, $procrescueCtr;
          } else {
            $monitorString = sprintf "%s %10.0f %s %s %7.3f %7.3f %7.3f %s %s %s %s %s %s %03d", 
                             $grbName, $grbGPS, $grbDate, $grbTime, $grbRA, $grbDec, $grbError, $ifoString, $grbSat, $jobCluster, $latency, $jobRunTime, $jobStatus, $rescueCtr;
            $sedCommand = sprintf "sed '%ds/.*/%s/' %s > %s", 
                     $lineNumber, $monitorString, $monitorStatusFile, $tempFile;
          }
          system $sedCommand;

          $cpCommand = sprintf "cp %s %s", $tempFile, $monitorStatusFile;
          system $cpCommand;
        #} else {
        #  #=== Append new GRB ===#
        #  if ($jobStatus eq 'PROCESSED') {
        #    printf PROCJOB "%-7s %-13s %13.3f %7.3f %7.3f %10s %12s %-9s %03d\n", 
        #                    $grbDate, $grbUT, $grbGPS, $grbRA, $grbDec, $jobCluster, $jobRunTime, $jobStatus, $rescueCtr;
        #  } else {
        #    printf MONSTAT "%-7s %-13s %13.3f %7.3f %7.3f %10s %12s %-9s %03d\n", 
        #                    $grbDate, $grbUT, $grbGPS, $grbRA, $grbDec, $jobCluster, $jobRunTime, $jobStatus, $rescueCtr;
        #  }
        }
        #=== Endif GRB has an entry in the monitor file ===#

        #=== Update search status web page ===#
        $searchStatusTable = {};
        $searchStatusTable->{'GRB_NAME'}    = $grbName;
        $searchStatusTable->{'GRB_GPS'}     = $grbGPS;
        $searchStatusTable->{'GRB_DATE'}    = $grbDate;
        $searchStatusTable->{'GRB_TIME'}    = $grbTime;
        $searchStatusTable->{'GRB_RA'}      = $grbRA;
        $searchStatusTable->{'GRB_DEC'}     = $grbDec;
        $searchStatusTable->{'GRB_ERR'}     = $grbError;
        $searchStatusTable->{'IFO_STRING'}  = $ifoString;
        $searchStatusTable->{'GRB_SAT'}     = $grbSat;
        $searchStatusTable->{'JOB_CLUSTER'} = $jobCluster;
        $searchStatusTable->{'LATENCY'}     = $latency;
        $searchStatusTable->{'RUN_TIME'}    = $jobRunTime;
        $searchStatusTable->{'JOB_STATUS'}  = $jobStatus;
        $searchStatusTable->{'RESCUE_CTR'}  = $rescueCtr;

        #foreach $tableKey (keys %$searchStatusTable) {
        #  printf "%s %s\n", $tableKey, $searchStatusTable->{$tableKey};
        #}

        $resultsLink = '';
        updateWebStatus($searchStatusTable,$htmlFile,$lineOffset,$resultsLink);
      }
      #=== Endif condor job was submitted, check on jobs ===#
    }
    #=== End loop through GRBs ===#

#  } else {

    #=== Sleep for a few minutes ===#
#    sleep $MONDELAY - $currentDelay;
#  }
  #=== Endif check if MONDELAY seconds has elapsed since last monitor ===#

  #=== Calculate time elapsed between now and last monitor ===#
#  $currentDelay = time - $previousTime;

#}

#=== End monitorGrb ===#
