#!/usr/bin/perl

require '/home/grb.exttrig/Online/O2/processor/exttrig_utils.pl';
require '/home/grb.exttrig/Online/O2/processor/exttrig_params.pl';

#=== Get user name ===#
$USERNAME = `whoami`;
chomp($USERNAME);

#=== Specify local working directories ===#
$HOMEDIR    = sprintf "/home/%s", $USERNAME;
$GRBDIR     = sprintf "%s/Online/%s/grbs", $HOMEDIR, $LIGORUN;
$SCRIPTSDIR = sprintf "%s/Online/%s/processor", $HOMEDIR, $LIGORUN;
$WEBDIR     = sprintf "%s/Online/%s/processor/web", $HOMEDIR, $LIGORUN;
$JOBSDIR    = sprintf "%s/runs/X", $SCRIPTSDIR;
$PUBSERVER_SED = $PUBSERVER;
my $find = "//";
my $replace = "\\/\\/";
$PUBSERVER_SED =~s/$find/$replace/g;
$RESULTSURL = sprintf "%s\\/~%s\\/grb\\/online\\/%s\\/search\\/results", $PUBSERVER_SED, $USERNAME, $LIGORUN;
$PUBLICDIR  = sprintf "%s/public_html/grb/online/%s/search/results", $HOMEDIR, $LIGORUN;
$MAINWEBDIR = sprintf "%s/~%s/grb/online/%s", $PUBSERVER, $USERNAME, $LIGORUN;
$MAINURL    = sprintf "%s/~%s/web/%s/OnlineGRB_page_%s.html", $PUBSERVER, $USERNAME, $LIGORUN, $LIGORUN;

#=== Specify output html file ===#
$htmlFile = sprintf "%s/OnlineGRB_page_%s.html", $WEBDIR, $LIGORUN;

#=== Specify line offset for job status line in html file ===#
$lineOffset = 5;

#=== Open input open-box status file ===#
$openboxFile = sprintf "%s/openboxjobs_%s.log", $SCRIPTSDIR, $LIGORUN;
$tempFile    = sprintf "%s/openboxjobs_%s_temp.log", $SCRIPTSDIR, $LIGORUN;
open OPENBOX, "<$openboxFile"
  or die "Error opening input open-box status file $openboxFile: $!";
chomp(@openboxJobs = <OPENBOX>);
close OPENBOX;

#=== Loop through GRBs ===#
foreach $openboxJob (@openboxJobs) {

  ($grbName,$grbGPS,$grbDate,$ifoString,$grbSat,$openjobCluster,$openjobStatus) = split(' ',$openboxJob);

  if ($openjobStatus ne 'PROCESSED') {
    #=== Set default open box link ===#
    $resultsLink = '';

    #=== Set default open box link ===#
    $openboxLink = '';

    $condorCommand = sprintf "condor_q -nobatch %d", $openjobCluster;
    @condorResult  = ();
    @condorResult  = `$condorCommand`;
    chomp(@condorResult);

    #=== If job is not found ===#
    #if ($#condorResult < 4) {
    if ($#condorResult < 6) {
      $failFetchFlag = 0;
      if ($#condorResult+1 == 0) {
        $failFetchFlag = 1;
      }
      if ($failFetchFlag == 0) {

        #=== Copy open-box files to public web directory ===#
        $AUTOWEB = sprintf "%s/GRB%s/auto_web", $JOBSDIR, $grbName;
        $HTMLDIR = sprintf "%s/%s_online", $PUBLICDIR, $grbName;

        #==for openbox event display page
        chdir "$AUTOWEB";
        $eventdisplay = sprintf "xgrbeventdisplay.py -a %s -t openbox", $AUTOWEB;
        system $eventdisplay;
        $eventdir = sprintf "%s/event", $AUTOWEB;
        chdir "$eventdir";
        $condorCommand2 = sprintf "condor_submit_dag grb_event_openbox.dag";
        system $condorCommand2;
        chdir "$SCRIPTSDIR";
        #===============================

        $cpCommand = sprintf "cp %s/%s_online_openbox.shtml %s/", $AUTOWEB, $grbName, $HTMLDIR;
        system $cpCommand;
        $cpCommand = sprintf "cp -r %s/%s_online_openbox_figfiles %s", $AUTOWEB, $grbName, $HTMLDIR;
        system $cpCommand;
        $cpCommand = sprintf "cp -r %s/%s_online_openbox_figures %s", $AUTOWEB, $grbName, $HTMLDIR;
        system $cpCommand;

        #=== Note finish time of analysis ===#
        $gpsTime    = `lalapps_tconvert now`;
        chomp($gpsTime);
        $timeString = `lalapps_tconvert $gpsTime`;
        chomp($timeString);

        #=== Calculate processing time in hours ===#
        $processTime = 0;
        $processTime = ($gpsTime - $grbGPS)/3600.0;
        $processTime = sprintf "%5.3f", $processTime;
        if ($processTime < 0) {
          $processTime = 0;
        }

        #=== Get line number of this GRB in the monitor file ===#
        $sedCommand = sprintf "sed -n '/^%s /=' %s", $grbName, $openboxFile;
        $lineNumber = -1;
        $lineNumber = `$sedCommand`;
        chomp($lineNumber);

        if ($lineNumber =~ /^[1-9]/) {
          $monitorString = sprintf "%s %10.0f %s %s %s %10s %-9s %11.5f %s", 
                                    $grbName, $grbGPS, $grbDate, $ifoString, $grbSat, $openjobCluster, 'PROCESSED', 
                                    $processTime, $timeString;
          $sedCommand = sprintf "sed '%ds/.*/%s/' %s > %s",
                        $lineNumber, $monitorString, $openboxFile, $tempFile;
          system $sedCommand;

          $cpCommand = sprintf "cp %s %s", $tempFile, $openboxFile;
          system $cpCommand;
        }

        #=== Specify link with results ===#
        $openboxLink = sprintf "%s\\/%s_online\\/%s_online_openbox.shtml", $RESULTSURL, $grbName, $grbName;

        #=== Update search status web page ===#
        $searchStatusTable = {};
        $searchStatusTable->{'GRB_NAME'} = $grbName;
        $searchStatusTable->{'IFO_STRING'}  = $ifoString;

        updateWebStatus($searchStatusTable,$htmlFile,$lineOffset,$resultsLink,$openboxLink);

        #=== Annotate the GraceDB external trigger event ===#
       if ($ANNOTATEFLAG eq 'YES') {
       $awkCommand = sprintf "awk 'c&&!--c;/Table of loudest surviving on-source events/{c=6}' %s/%s_online_openbox.shtml", $AUTOWEB, $grbName;
       $awkComandResult = -1;
       $awkComandResult = `$awkCommand`;
       chomp($awkComandResult);
       
       my @stuff = $awkComandResult =~ />([^<]+)</g;
       $statistics = join (" ", @stuff);
       $probability = @stuff[1];
       if ($ifoString eq 'H1L1') {
       $peakGPS = @stuff[14];
       } else {
       $peakGPS = @stuff[7];
       }
       if ($probability >= 0 and $probability <= $FAP_TH and $probability ne "") {
         $probability = sprintf("%.6f", $probability);
         $annotateFile = sprintf "%s/annotateGraceDB_X_event_template.py", $SCRIPTSDIR;
         $catCommand = sprintf "cat %s | sed -e 's/EVENT_ID/%s/g' -e 's/USERNAME/%s/g' -e 's/LIGORUN/%s/g' -e 's/PROBABILITY_VAL/%s/g' -e 's/PUBSERVER/%s/g'> annotateGraceDB.py", $annotateFile, $grbName, $USERNAME, $LIGORUN, $probability, $PUBSERVER_SED;
         system $catCommand;
         $annotateCommand = sprintf "python annotateGraceDB.py";
         system $annotateCommand;
         $rmCommand = sprintf "rm -f annotateGraceDB.py";
         system $rmCommand;
       } else {
         if ($probability >= 0 and $probability > $FAP_TH and $probability ne "") {
         $probability = $probability;
         $probability = sprintf("%.6f", $probability);
         } else {
         $probability = "NaN";
         }
         $annotateFile = sprintf "%s/annotateGraceDB_X_noevent_template.py", $SCRIPTSDIR;
         $catCommand = sprintf "cat %s | sed -e 's/EVENT_ID/%s/g' -e 's/USERNAME/%s/g' -e 's/LIGORUN/%s/g' -e 's/PROBABILITY_VAL/%s/g' -e 's/PUBSERVER/%s/g'> annotateGraceDB.py", $annotateFile, $grbName, $USERNAME, $LIGORUN, $probability, $PUBSERVER_SED;
         system $catCommand;
         $annotateCommand = sprintf "python annotateGraceDB.py";
         system $annotateCommand;
         $rmCommand = sprintf "rm -f annotateGraceDB.py";
         system $rmCommand;
      }
     
       #=== Do Omega scan for loudest event and annotate GraceDB =====#
       if ($probability ne "" or $probability ne 'NaN') { 
       if ($ifoString eq 'H1L1') {
         $ifo_H1 = "H1";
         $OmegaScan = sprintf "nohup /home/grb.exttrig/wdq/%s/wdqER %s %s > /home/grb.exttrig/wdq/%s/log/%s_%s.txt &",$LIGORUN,$ifo_H1,$peakGPS,$LIGORUN,$ifo_H1,$peakGPS;
         system $OmegaScan;
         $annotateFile = sprintf "%s/annotateGraceDB_X_omega_template.py", $SCRIPTSDIR;
         $catCommand = sprintf "cat %s | sed -e 's/EVENT_ID/%s/g' -e 's/USERNAME/%s/g' -e 's/LIGORUN/%s/g' -e 's/IFO/%s/g' -e 's/GPS/%s/g' -e 's/PUBSERVER/%s/g'> annotateGraceDB.py", $annotateFile, $grbName, $USERNAME, $LIGORUN, $ifo_H1, $peakGPS, $PUBSERVER_SED;
         system $catCommand;
         $annotateCommand = sprintf "python annotateGraceDB.py";
         system $annotateCommand;
         $rmCommand = sprintf "rm -f annotateGraceDB.py";
         system $rmCommand;
         
         $ifo_L1 = "L1";
         $OmegaScan = sprintf "nohup /home/grb.exttrig/wdq/%s/wdqER %s %s > /home/grb.exttrig/wdq/%s/log/%s_%s.txt &",$LIGORUN,$ifo_L1,$peakGPS,$LIGORUN,$ifo_L1,$peakGPS;
         system $OmegaScan;
         $annotateFile = sprintf "%s/annotateGraceDB_X_omega_template.py", $SCRIPTSDIR;
         $catCommand = sprintf "cat %s | sed -e 's/EVENT_ID/%s/g' -e 's/USERNAME/%s/g' -e 's/LIGORUN/%s/g' -e 's/IFO/%s/g' -e 's/GPS/%s/g' -e 's/PUBSERVER/%s/g'> annotateGraceDB.py", $annotateFile, $grbName, $USERNAME, $LIGORUN, $ifo_L1, $peakGPS, $PUBSERVER_SED;
         system $catCommand;
         $annotateCommand = sprintf "python annotateGraceDB.py";
         system $annotateCommand;
         $rmCommand = sprintf "rm -f annotateGraceDB.py";
         system $rmCommand;
        } else {
         $OmegaScan = sprintf "nohup /home/grb.exttrig/wdq/%s/wdqER %s %s > /home/grb.exttrig/wdq/%s/log/%s_%s.txt &",$LIGORUN,$ifoString,$peakGPS,$LIGORUN,$ifoString,$peakGPS;
         system $OmegaScan;
         $annotateFile = sprintf "%s/annotateGraceDB_X_omega_template.py", $SCRIPTSDIR;
         $catCommand = sprintf "cat %s | sed -e 's/EVENT_ID/%s/g' -e 's/USERNAME/%s/g' -e 's/LIGORUN/%s/g' -e 's/IFO/%s/g' -e 's/GPS/%s/g' -e 's/PUBSERVER/%s/g'> annotateGraceDB.py", $annotateFile, $grbName, $USERNAME, $LIGORUN, $ifoString, $peakGPS, $PUBSERVER_SED;
         system $catCommand;
         $annotateCommand = sprintf "python annotateGraceDB.py";
         system $annotateCommand;
         $rmCommand = sprintf "rm -f annotateGraceDB.py";
         system $rmCommand;
         }} else {
         $OmegaScan = "Null";
         }

         }

        &sendResultsMessage;
      }
    }
  }
  #=== Endif status is not PROCESSED ===#
}

sub sendResultsMessage {

  $emailsFile   = sprintf "%s/eventadvocate/%s_grbemails.txt", $SCRIPTSDIR, $grbName;
  $messagesFile = sprintf "%s/grbmessages_%s.log", $SCRIPTSDIR, $LIGORUN;

  #=== Specify pages with results ===#
  $resultsPageClosed = sprintf "%s/search/results/%s_online/%s_online_closedbox.shtml", $MAINWEBDIR, $grbName, $grbName;
  $resultsPageOpen   = sprintf "%s/search/results/%s_online/%s_online_openbox.shtml", $MAINWEBDIR, $grbName, $grbName;

  $eheaderTable = {};
  $eheaderTable->{'SUBJECT'} = sprintf "[X-pipeline] GRB %s open-box", $grbName;

  #=== Construct the message ===#
  $noticeString = sprintf "GRB %s box has been opened, %8.3f hours after the trigger.", 
                               $grbName, $processTime;
  $noticeString = sprintf "%s\n\nClosed box results:", $noticeString;
  $noticeString = sprintf "%s\n<%s>", $noticeString, $resultsPageClosed;
  $noticeString = sprintf "%s\n\nOpen box results:", $noticeString;
  $noticeString = sprintf "%s\n<%s>", $noticeString, $resultsPageOpen;
  $noticeString = sprintf "%s\n\nMain results page:", $noticeString;
  $noticeString = sprintf "%s\n<%s>\n", $noticeString, $MAINURL;

  $eheaderTable->{'MESSAGE'} = $noticeString;

  printf "$noticeString\n";

  #=== Send the message ===#
  grbNotify($eheaderTable,$emailsFile,$messagesFile);
}

#=== End monitorOpenJobs ===#
